### ISSUE TITLE
Add costume message for matrics

### ISSUE THREAD

**Issue by Rysakov1986** [voiceip/tinyphone#12]
Greetings! 
_Sorry, but within a couple of days, I have not been able to check answer on incoming calls, but as soon as this opportunity arises, I will definitely check! :)_

And now, I want to ask you to add the ability to send a costume message in the matrics. I think **POST** `/matrics`,
body:
```json
{
  "action": "open",
  "message": "text message"
} 
```

and this is sent to matrics.

example:
tinyphone.[action]: [message]|c|# version = 36.0.0.79

out: 
tinyphone.open:text message|c|# version = 36.0.0.79

Thanks!

**Comment by kingster** [comment]
Didn't exactly get what you wanted here. 

StatsD Endpoint doesn't understand textual payloads, only [numeric ones are supported](https://sysdig.com/blog/monitoring-statsd-metrics/), maybe you can explain exactly what you are trying to achieve?

**Comment by Rysakov1986** [comment]
I create my metrics app server (nodejs) and forward message for me and control status tinyphone and more if support costume message)

**Comment by kingster** [comment]
In that case I will suggest that you can directly send the http request to your nodejs server, instead of using tinyphone as a relay.

I am closing this issue, as this isn't a bug and instead can become a vulnerability given that this would become an open udp/tcp  relay. If you still think that this is valid feature request, please reopen the ticket with more details.
