### ISSUE TITLE
Feature : conference between selective parties

### ISSUE THREAD

**Issue by ploufs** [voiceip/tinyphone#63]
On softphone have 3 calls.
Only conference between call 1 and 2.

Suggest new ressource : /calls/conference
Payload : Array call_Id

**Comment by kingster** [comment]
This could possibly be an enhancement. Though I really can't think of a scenario where this would be required. Could you share an example scenario where this would be used?

**Comment by ploufs** [comment]
Softphone = receptionist
Call 1 = Customer 1
Call 2 = Sale
Call 3 = Customer 2

Receptionist does conference customer 1 with sale and exist calls.

**Comment by ploufs** [comment]
https://www.pjsip.org/docs/1.16/pjsip/docs/html/group__PJSUA__LIB__CALL.htm#gaa8c781210e8c2b24183cb3c5215c68d7

function pjsua_call_xfer_replaces in pjsua ?

**Comment by kingster** [comment]
If I understand this correctly, this also relates to #65 where in 3 party conference the receptionist would conference and then drop out of the call. 



> https://www.pjsip.org/docs/1.16/pjsip/docs/html/group__PJSUA__LIB__CALL.htm#gaa8c781210e8c2b24183cb3c5215c68d7
> 
> function pjsua_call_xfer_replaces in pjsua ?

Yes this would be the function that implements, and need to be called instead of hangup when exiting the conference. That way the 2 parties would continue the direct call between them.

**Comment by ploufs** [comment]
@kingster  Do you plan to develop this functionality soon?

**Comment by kingster** [comment]
@ploufs Some parts of this might not be straightforward, since this would mean the phone would have to support multiple conferences and keep track of the running conferences, this IMO overlaps with the functionality of a dedicated conference server/PBX. 

That said, an attended transfer of call is something that makes sense (the reception example, with 2 calls only), and I will pick it up when I get some time soon.
