### ISSUE TITLE
No voice in call

### ISSUE THREAD

**Issue by thiva7** [voiceip/tinyphone#79]
Hey.
I have installed your app but in call I cant listen anything.
I try it In a laptop to make sure is not something that have to do with my main pc and same happen.
Is something related to config file? To setup devices?

Thanks

**Comment by kingster** [comment]
Yes, it would be probably related to the configuration. If you are behind NAT and your service provider is a public, you would need to enable STUN so that the voice can traverse properly. Inversely if your SIP server is internal in your lan network, you would need to disable stun. Please spend time in configuring the pjusa client accordingly to your network setup.
